# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React  CI

on:
  push
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      -   name: Run a one-line script
          uses: actions/checkout@v2

      -   name: Install Vue Dependencias
          run: yarn install

      -   name: Check code with EsLint 
          run: yarn lint

      -   name: Check code with Prettier
          run: yarn prettier

      -   name: Build React APP
          run: cd frontend && yarn build
